server:
  port: 8181

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:9092} # Cambiado de 127.0.0.1:9092
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      #retries: 3
      #request-timeout-ms: 30000
      #delivery-timeout-ms: 120000
      properties:
        schema:
          registry:
            url: "http://schema-registry:8081"  # Cambiado de 127.0.0.1:8081
    consumer:
      group-id: "prueba-new"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      enableAutoCommit: true
      #session-timeout-ms: 30000
      #heartbeat-interval-ms: 3000
      #request-timeout-ms: 30000
      properties:
        schema:
          registry:
            url: "http://schema-registry:8081"  # Cambiado de 127.0.0.1:8081
        specific:
          avro:
            reader: "true"
